# Generated by Django 2.2.6 on 2020-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200731_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employed',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notemployed',
            name='position',
            field=models.CharField(max_length=200),
        ),
    ]
