apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: postgres:12.0-alpine
    generation: null
    importPolicy: {}
    name: 12.0-alpine
status:
  dockerImageRepository: ""
